### ISSUE TITLE
WebService requires UserProfile instances to set their context to null

### ISSUE THREAD

**Issue by ioltuszyk** [CMPUT301F17T05/Habilect#1]
Should use Map or Json strings, as opposed to POJO. By removing the context, future calls to UserProfile.Lookup will crash the application.

**Comment by StevenYLChan** [comment]
As another hacky workaround we could temporarily store the context in a variable then add it back in after the web service call.

**Comment by ioltuszyk** [comment]
UserProfile has been deprecated in favor of UserAccount; issue no longer requires action.
